### ISSUE TITLE
Add tests that could generate negative values in the pmatrix.

### ISSUE THREAD

**Issue by xflouris** [xflouris/libpll#129]
If the exponentials `E` of the products of `eigenvalues[i] * branch_length * rate` for every state i are very close to 1, then the pmatrix is the matrix product of the eigenvectors matrix multiplied with the inverse eigenvectors matrix, which is equiv. to the identity matrix. However, for `E` very close to 1, this can generate negative numbers in the pmatrix.

Add tests that cause such problems, to verify that our fix 9a4e48e17c1916b4b6535c9309aa5d64216ffc83.

See also issue #125 .

**Comment by amkozlov** [comment]
i added a comprehensive test (23f80cca787288cb5f18fc9d4648757ebaea9a02) which covers different
- datatypes (DNA, AA, 5-state model)
- stationary frequencies (equal, slightly skewed, extremely skewed)
- substitution matrices (equal, slightly skewed, extremely skewed)
- category rates (low, medium, high)
- branch lengths (short, medium, long)

in all combinations.

**NOTE:** Currently, this test will fail since solution from #125 doesn't seem to work in all cases. Please see my comment in  #125 for details.

**Comment by bredelings** [comment]
Hi,

     Is the problem in #125 that you get inaccurate values of exp(Q*t) 
when t is very small?  I just ran into this problem, and was able to 
find a solution by computing [exp(Q*t) - I] instead. If its of interest, 
I can explain my solution.

-BenRI

**Comment by amkozlov** [comment]
Hi Ben,

yes, that's the problem we have, could you please explain your solution?

**Comment by bredelings** [comment]
Hi Alexey,

The C function expm1(double x) exists to calculate exp(x)-1 when x is 
small.  For these cases exp(x)-1 should be approximately x. If we 
compute exp(x) - 1.0 we will get 0 because of roundoff error, but 
expm1(x) will be about x.

The general idea of my solution is to compute a matrix version of 
expm1(Q*t) = exp(Q*t) - I.  Then we can add I to it and get
     exp(Q*t) = I + expm1(Q*t).
For small values of t, expm1(Q*t) should be proportional to t, so that 
when t=0 we will recover the identity matrix exactly.

Surprisingly, when using an eigenvalue decomposition where the 
eigenvalues are d[i], we can just compute expm1(d[i]) instead of 
exp(d[i]) to get expm1(Q*t).  The last bit of the attached PDF shows why 
this is allowed.

You can see an example implementation here:
https://github.com/bredelings/BAli-Phy/blob/master/src/math/exponential.C

I hope that helps!

I have not checked how this affects the negative values directly, so I'd 
be interested to hear how it affects that, as well as the other problem 
cases for Q.

-BenRI

**Comment by amkozlov** [comment]
Thanks a bunch, Ben - you saved my day! :) it seems to work perfectly on all our test cases, all negative values are gone.

Just for our reference: could you please attach the PDF you've mentioned above? I can't see it.

Thanks again!

**Comment by bredelings** [comment]
Yay!  (Here's the PDF).
[expm1.pdf](https://github.com/xflouris/libpll/files/1030469/expm1.pdf)

**Comment by amkozlov** [comment]
great, thanks!

**Comment by ziheng-yang** [comment]
good idea.  the spectral decomposition part is 
the same as section 2.6 of my book, but it seems 
that calculation of exp Qt - I helps with 
numerical stability.  i suppose exp Dt - I is diag{ exp d_i t - 1}.
the order of multiplications may affect computation.
ziheng



At 16:54 25/05/2017 -0700, Benjamin Redelings wrote:
